insert into role(ROLE) values ('ROLE_ADMIN');
insert into role(ROLE) values ('ROLE_RECEPCIONISTA');
insert into role(ROLE) values ('ROLE_AUXILIAR');
insert into role(ROLE) values ('ROLE_MEDICO');

insert into funcionario(NOME_FUNCIONARIO, CPF_FUNCIONARIO, RG_FUNCIONARIO,DATA_NASCIMENTO_FUNCIONARIO, ENDERECO_FUNCIONARIO, CEP_FUNCIONARIO, BAIRRO_FUNCIONARIO,CIDADE_FUNCIONARIO, ESTADO_FUNCIONARIO, TELEFONE_FUNCIONARIO, EMAIL_FUNCIONARIO,FUNCAO, LOGIN_FUNCIONARIO, SENHA_FUNCIONARIO) VALUES ('ERIKA MARIA TAVEIRA DOS SANTOS TEIXEIRA','046.754.373-97', '2008010067430', TO_DATE('1998-07-21', 'YYYY-MM-DD'), 'RUA DOS ARARIUS, 200, APT 803', '60060-320','PRAIA DE IRACEMA', 'FORTALEZA', 'CE', '(85) 9 9623-0391', 'erikamsantos98@gmail.com', 'ADMIN','ERIKA.TEIXEIRA', '$2a$10$VZDkw0.Kd.QC1PvlwKdU3OOHWIcgl3yopD5BIMOtV/GKqq2OiNd46');
insert into funcionario(NOME_FUNCIONARIO, CPF_FUNCIONARIO, RG_FUNCIONARIO,DATA_NASCIMENTO_FUNCIONARIO, ENDERECO_FUNCIONARIO, CEP_FUNCIONARIO, BAIRRO_FUNCIONARIO,CIDADE_FUNCIONARIO, ESTADO_FUNCIONARIO, TELEFONE_FUNCIONARIO, EMAIL_FUNCIONARIO,FUNCAO, LOGIN_FUNCIONARIO, SENHA_FUNCIONARIO) VALUES ('JOANA DARC TAVEIRA DOS SANTOS','139.847.303-06', '02145427430', TO_DATE('1955-06-14', 'YYYY-MM-DD'), 'RUA DOS ARARIUS, 200, APT 803', '60060-320','PRAIA DE IRACEMA', 'FORTALEZA', 'CE', '(85) 9 9613-3615', 'joanad.ceara@gmail.com', 'RECEPCIONISTA','JOANA.SANTOS', '$2a$10$Goce/ZsSVC8wwt5jdEg4AO1t6xvGUy5tOQgMwBNkOwDE/j0iaszX6');
insert into funcionario(NOME_FUNCIONARIO, CPF_FUNCIONARIO, RG_FUNCIONARIO,DATA_NASCIMENTO_FUNCIONARIO, ENDERECO_FUNCIONARIO, CEP_FUNCIONARIO, BAIRRO_FUNCIONARIO,CIDADE_FUNCIONARIO, ESTADO_FUNCIONARIO, TELEFONE_FUNCIONARIO, EMAIL_FUNCIONARIO,FUNCAO, LOGIN_FUNCIONARIO, SENHA_FUNCIONARIO) VALUES ('SHEILA MENDES SILVA','147.847.303-06', '13375427430', TO_DATE('1980-07-14', 'YYYY-MM-DD'), 'RUA DOS ARARIUS, 200, APT 803', '60060-320','PRAIA DE IRACEMA', 'FORTALEZA', 'CE', '(85) 9 9858-3615', 'sheila@gmail.com', 'AUXILIAR', null , null);

insert into funcionario_role(ID_FUNCIONARIO, ID_ROLE) VALUES (1,1);
insert into funcionario_role(ID_FUNCIONARIO, ID_ROLE) VALUES (2,2);
insert into funcionario_role(ID_FUNCIONARIO, ID_ROLE) VALUES (3,3);

insert into paciente(NOME_PACIENTE, CPF_PACIENTE, PASSAPORTE_PACIENTE, DATA_NASCIMENTO_PACIENTE, NOME_RESPONSAVEL, CPF_RESPONSAVEL, GENERO, ENDERECO_PACIENTE, CEP_PACIENTE, BAIRRO_PACIENTE,CIDADE_PACIENTE, ESTADO_PACIENTE, TELEFONE_PACIENTE, EMAIL_PACIENTE,PLANO_SAUDE, NUM_PLANO, VALIDADE_PLANO) VALUES ('MARIANA ALVES MELLO','138.754.373-97', null , TO_DATE('1991-05-17', 'YYYY-MM-DD'), null , null , 'FEMININO', 'RUA DOS ARARIUS, 200, APT 803', '60060-320','PRAIA DE IRACEMA', 'FORTALEZA', 'CE', '(85) 9 9874-0391', 'mariana@gmail.com', 'UNIMED', '16648547', TO_DATE('2024-08-15', 'YYYY-MM-DD'));
insert into paciente(NOME_PACIENTE, CPF_PACIENTE, PASSAPORTE_PACIENTE, DATA_NASCIMENTO_PACIENTE, NOME_RESPONSAVEL, CPF_RESPONSAVEL, GENERO, ENDERECO_PACIENTE, CEP_PACIENTE, BAIRRO_PACIENTE,CIDADE_PACIENTE, ESTADO_PACIENTE, TELEFONE_PACIENTE, EMAIL_PACIENTE,PLANO_SAUDE, NUM_PLANO, VALIDADE_PLANO) VALUES ('PEDRO SILVA AZEVEDO', null, '2024845662' , TO_DATE('1956-10-15', 'YYYY-MM-DD'), null , null, 'MASCULINO', 'RUA DOS ARARIUS, 200, APT 803', '60060-320','PRAIA DE IRACEMA', 'FORTALEZA', 'CE', '(85) 9 9999-0391', 'pedro@gmail.com', 'PARTICULAR', 'null' , null);

insert into medico(NOME_MEDICO, CNPJ, CRM_ESTADO, CRM_NUM, TELEFONE_MEDICO, EMAIL_MEDICO, ESPECIALIDADE, SALA, LOGIN_MEDICO, SENHA_MEDICO, HORA_INICIAL, HORA_FINAL, VALOR_CONSULTA) VALUES ('BIANCA MEDEIROS FONTES','33.525.154/0001-14', 'CE', '123456', '(85) 9 9713-0391', 'bianca@gmail.com', 'GINECOLOGISTA', '01', 'BIANCA.FONTES', '$2a$10$0tVLkxzN8upQZySz.TDjHuOA8ObTVqb2U/eB0WM5B2jc3bHI.OEKS',TO_TIMESTAMP('2023-06-15 14:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2023-06-15 18:00:00', 'YYYY-MM-DD HH24:MI:SS'), 250);
insert into medico(NOME_MEDICO, CNPJ, CRM_ESTADO, CRM_NUM, TELEFONE_MEDICO, EMAIL_MEDICO, ESPECIALIDADE, SALA, LOGIN_MEDICO, SENHA_MEDICO, HORA_INICIAL, HORA_FINAL, VALOR_CONSULTA) VALUES ('BRUNO ANDRADE DO SANTOS','55.741.334/0001-24', 'CE', '257456', '(85) 9 8883-0391', 'bruno@gmail.com', 'CARDIOLOGISTA', '02', 'BRUNO.SANTOS', '$2a$10$OfXC3fSvqJzEgds8HeVO9.wAykzkDu63.B/VdrP4Gxvz365o062aO', TO_TIMESTAMP('2023-06-15 08:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2023-06-15 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), 300);

insert into medico_dia_semana(ID_MEDICO, DIA_SEMANA) VALUES (1, 'SEGUNDA');
insert into medico_dia_semana(ID_MEDICO, DIA_SEMANA) VALUES (1, 'QUARTA');
insert into medico_dia_semana(ID_MEDICO, DIA_SEMANA) VALUES (2, 'TERCA');
insert into medico_dia_semana(ID_MEDICO, DIA_SEMANA) VALUES (2, 'QUINTA');

insert into medico_role(ID_MEDICO, ID_ROLE) VALUES (1,4);
insert into medico_role(ID_MEDICO, ID_ROLE) VALUES (2,4);

insert into consulta(DATA_CONSULTA, HORA_CONSULTA, RETORNO_CONSULTA, ID_MEDICO, ID_FUNCIONARIO, ID_PACIENTE) VALUES (TO_DATE('2023-06-15', 'YYYY-MM-DD'), TO_TIMESTAMP('2023-06-15 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), 0, 2, 1, 1);
insert into consulta(DATA_CONSULTA, HORA_CONSULTA, RETORNO_CONSULTA, ID_MEDICO, ID_FUNCIONARIO, ID_PACIENTE) VALUES (TO_DATE('2023-06-15', 'YYYY-MM-DD'), TO_TIMESTAMP('2023-06-15 10:30:00', 'YYYY-MM-DD HH24:MI:SS'), 1, 1, 2, 2);